### ISSUE TITLE
Yazarın son entryleri fonksiyonu çalışmıyor

### ISSUE THREAD

**Issue by expeditor** [onuraslan/EksiOkuyucu#1]
herhangi bir yazarın son entrylerini görüntüleme fonksiyonu çoğu zamana çalışmıyor, yükleniyor olarak kalıyor.

http://eksi.ninja/#tl/basliklar/istatistik/ssg/son-entryleri

**Comment by onur** [comment]
Bende bir sıkıntı olmadan açıldı. Bazen ekşi cevap veremiyor isteklere, veya bir tema çakışması nedeniyle parser çalışmamış olabilir.

**Comment by expeditor** [comment]
Biraz kurcalayınca sebebini yakaladım.
EksiOkuyucu iki veya daha fazla kelimeden oluşan kullanıcı adlarını `%20` ile ayırıyor. Ancak gitmesi gereken requestte ayırıcı `-` olması gerekiyor.

Sanırım [şurada](https://github.com/onuraslan/EksiOkuyucu/blob/9b4e1c198c366761ef5930f237226d230ce36311/app/js/views/search.js#L62) ufak bir rötüş gerekiyor.

**Comment by onur** [comment]
Evet dediğiniz doğru hata raporu için teşekkürler.

Bunu, zamanında geliştirirken Ekşisözlük kullanıcı adlarının yer aldığı bağlantılarda `-` yerine `%20` kullanıyordu. Ekşisözlük şu anda bile `%20` olarak da kabul ediyor (örneğin: `https://eksisozluk.com/basliklar/istatistik/10%20kere%20dedim%20anlamadiniz/son-entryleri` ama link yapılarının değişmesinden ötürü eksi.ninja üzerinde yer alan reverse proxy de bir sorun var. Sürekli `400` döndürüyor arasında boşluk olan kullanıcı adları için.

Zaman bulursam düzelteceğim.

**Comment by onur** [comment]
Sanırım sorun çözüldü.

**Comment by expeditor** [comment]
Yep.
